---
- name: WordPress on Nginx, PHP-FPM, MariaDB

  hosts: webservers
  remote_user: ubuntu
  sudo: yes
  vars:
    wp_php_fpm: true
    fpm_start: true
    wp_advanced: true

  roles:
    - common
    - mariadb
    - php
    - php-fpm
    - nginx
    - wp-cli
    - wordpress-install
